# Generated by Django 6.0.1 on 2026-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(verbose_name='详细描述')),
                ('category', models.CharField(choices=[('hardware', '硬件问题'), ('software', '软件问题'), ('network', '网络问题'), ('permission', '权限问题'), ('other', '其他')], max_length=20, verbose_name='问题类型')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('employee_id', models.CharField(max_length=50, verbose_name='员工工号')),
                ('employee_name_snapshot', models.CharField(max_length=100, verbose_name='员工姓名快照')),
                ('department_snapshot', models.CharField(max_length=100, verbose_name='部门快照')),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='分配给（IT工程师工号）')),
                ('attachments', models.JSONField(blank=True, default=list, verbose_name='附件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('estimated_resolution_time', models.DateTimeField(blank=True, null=True, verbose_name='预计解决时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='实际解决时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id'], name='tickets_employe_c7425e_idx'), models.Index(fields=['status'], name='tickets_status_fbbf05_idx'), models.Index(fields=['category'], name='tickets_categor_df3afb_idx'), models.Index(fields=['created_at'], name='tickets_created_ed60df_idx')],
            },
        ),
    ]
