# Generated by Django 6.0.1 on 2026-01-24 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='员工工号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('department', models.CharField(max_length=100, verbose_name='部门')),
                ('role', models.CharField(choices=[('employee', '普通员工'), ('it_staff', 'IT人员'), ('admin', '管理员')], default='employee', max_length=20, verbose_name='角色')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='办公地点')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否在职')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工',
                'db_table': 'employees',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_category', models.CharField(max_length=20, verbose_name='建议分类')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='置信度')),
                ('suggested_solution', models.TextField(verbose_name='建议解决方案')),
                ('similar_tickets', models.JSONField(blank=True, default=list, verbose_name='相似历史工单')),
                ('model_used', models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='使用的模型')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True, verbose_name='处理时间(毫秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='ticketing.ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
                'db_table': 'ai_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('category', models.CharField(choices=[('hardware', '硬件问题'), ('software', '软件问题'), ('network', '网络问题'), ('permission', '权限问题'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('embedding', models.TextField(blank=True, null=True, verbose_name='向量嵌入')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='成功率')),
                ('created_by', models.CharField(max_length=50, verbose_name='创建人工号')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'db_table': 'knowledge_base',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='knowledge_b_categor_a5a4af_idx'), models.Index(fields=['usage_count'], name='knowledge_b_usage_c_57c944_idx')],
            },
        ),
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_field', models.CharField(max_length=50, verbose_name='变更字段')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='旧值')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='新值')),
                ('changed_by', models.CharField(max_length=50, verbose_name='操作人工号')),
                ('comment', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='ticketing.ticket', verbose_name='关联工单')),
            ],
            options={
                'verbose_name': '工单历史',
                'verbose_name_plural': '工单历史',
                'db_table': 'ticket_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket'], name='ticket_hist_ticket__1508d0_idx'), models.Index(fields=['changed_by'], name='ticket_hist_changed_acbb8c_idx'), models.Index(fields=['created_at'], name='ticket_hist_created_c58864_idx')],
            },
        ),
    ]
