# Generated by Django 6.0.1 on 2026-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_employee_airesponse_knowledgebase_tickethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attachments',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='附件'),
        ),
    ]
