# Generated by Django 6.0.1 on 2026-01-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_alter_ticket_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='描述向量'),
        ),
        migrations.AlterField(
            model_name='airesponse',
            name='model_used',
            field=models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='使用的模型'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='embedding',
            field=models.JSONField(blank=True, null=True, verbose_name='向量嵌入'),
        ),
    ]
